#!bin/busybox ash
# (C) Dieter Miosga 08.2013 - 31.03.2014
source /etc/functions-ash-dm
mkramdisk
MSGFILE=/ramdisk/msg.log
INITPREF="0 in $0"
source general-functions
source initvariables
source yainitdefaults
source modprobe-functions
MODULES1=""
MODULES2=""
MODULES3="" 
export MODULES2LOAD=""
i=""
for i in 1 2; do
   INITPREF="[ $i in $0 ]: " 
   echoconsole "$INITPREF" "from modaliases direct a la Dieter"
   startts
   j=""
   for j in 0 1 2 3 4 5 6 7 8 9; do
     echofile "$INITPREF" "from modaliases direct a la Dieter"
     MODULES2LOAD=""
     find_drivers_with_aliases 
     find_drivers_refine
     remove_duplicates_from_string "MODULES2LOAD"
     kernelmodules_order
     echofile "$INITPREF" "modules : '$MODULES2LOAD'"
     MODULES1="$MODULES2LOAD"
   done 
   stopts
   timediff
   MODULES1="$MODULES2LOAD"
   echoconsole "$INITPREF" "find fast a la Android"
   startts
   j=""
   for j in 0 1 2 3 4 5 6 7 8 9; do
     echofile "$INITPREF" "find fast a la Android"
     MODULES2LOAD=""
     find_drivers_with_aliases_fast
     find_drivers_refine 
     remove_duplicates_from_string "MODULES2LOAD"
     kernelmodules_order
     echofile  "$INITPREF" "modules : '$MODULES2LOAD'"
     MODULES2="$MODULES2LOAD"
   done 
   stopts
   timediff
   MODULES2="$MODULES2LOAD"
   echoconsole "$INITPREF" "find a la uevents"
   startts
   j=""
   for j in 0 1 2 3 4 5 6 7 8 9; do
     echofile "$INITPREF" "find a la uevents"
     MODULES2LOAD=""
     find_drivers_from_uevents /sys
     find_drivers_refine
     remove_duplicates_from_string "MODULES2LOAD"
     kernelmodules_order
     echofile "$INITPREF" "modules : '$MODULES2LOAD'"
     MODULES3="$MODULES2LOAD"
   done 
   stopts
   timediff
   MODULES3="$MODULES2LOAD"
done

rm  /ramdisk/modules1.txt
rm  /ramdisk/modules2.txt
rm  /ramdisk/modules3.txt

for mod in $MODULES1; do
echo "$mod" >> /ramdisk/modules1.txt
done
for mod in $MODULES2; do
echo "$mod" >> /ramdisk/modules2.txt
done
for mod in $MODULES3; do
echo "$mod" >> /ramdisk/modules3.txt
done

sleep 1
mkdiffs /ramdisk/modules1.txt /ramdisk/modules2.txt 2>/dev/null
mkdiffs /ramdisk/modules2.txt /ramdisk/modules3.txt 2>/dev/null
mkdiffs /ramdisk/modules1.txt /ramdisk/modules3.txt 2>/dev/null

#

