#!bin/busybox ash
# (C) Dieter Miosga 08.2013 - 3.12.2013
EXTENT="$2"
VERSION="$1"
MODF=""
MKEXTENT="xz"
ALLMODF=""
ALLMKEXTENTS="gz xz bz2 lzma lz"

if [ -e general-functions ]; then
  source general-functions
else
  echo "essential functions from file 'general-functions' cannot be read!"
  echo "exiting (127)"
  exit 127
fi

inline_external_file "initvariables"
inline_external_file "yainitdefaults"
inline_external_file "BLACKLIST_MODULES"
inline_external_file "WHITELIST_MODULES"


  
if [ "$BLACKLIST_MODULES" != "" ]; then
   echo "Blacklisted Modules found!"
   MODULES=""
  if [ "$DEFAULT_ALLDRIVERS" != "" -a "$WHITELIST_MODULES" != "" ]; then
   for mod in $DEFAULT_ALLDRIVERS $WHITELIST_MODULES; do
     if `is_substring_of "$mod" "$BLACKLIST_MODULES"`; then
       MODULES="$MODULES $mod"
     fi
   done
   if [ "$MODULES" != "" ]; then
     echo "Found by blacklist forbidden modules:"
     echo "$MODULES"
   else
     echo "...done successfully. No blacklisted modules in configuration file!" 
   fi
  else
     echo "No variable DEFAULT_ALLDRIVERS and/or WHITELIST_MODULES found! "
  fi
else
   echo "No file with Blacklisted Modules found! "
fi

   echo "$0 ended!"

exit 0
#

