#!bin/busybox ash
# (C) Dieter Miosga 08.2013 - 31.10.2013 
LSMODULES=`/bin/busybox lsmod  | /bin/busybox cut -f1 -d" " 2>/dev/null | /bin/busybox tr "\n\t" " " 2>/dev/null`
# cut the first token. It contains the header "Module" from lsmod command output.
MODULES_LOCAL="`echo $LSMODULES | /bin/busybox cut -f2- -d" " 2>/dev/null `" 
LSMODULES=`/bin/busybox lspci -k  | /bin/busybox cut -f5 -d" " 2>/dev/null | /bin/busybox tr "\n\t  " " " 2>/dev/null`
MODULES_LOCAL="$LSMODULES $MODULES_LOCAL"
echo MODULES_LOCAL=\"$MODULES_LOCAL\" > MODULES_LOCAL
#

