#!bin/busybox ash
#read_initrdvar_file
EXTENT="$1"
MODF=0
ALLMODF=""

. yainitdefaults


if [ "$INITRD" != "" ]; then
 if [ "$EXTENT" != "" ]; then INITRD="$INITRD-$EXTENT"; fi 
 echo "  initrd name = $INITRD"
 bin/busybox rm ../$INITRD.lzm
 bin/busybox sync
 bin/busybox find . | bin/busybox cpio -o -H newc | /usr/bin/lzma -9 > ../$INITRD.lzm
else
 bin/busybox rm ../yainit0.lzma
 bin/busybox sync
 bin/busybox find . | bin/busybox cpio -o -H newc | /usr/bin/lzma  -9 > ../yainit0.lzma
fi
 bin/busybox sync
 
 if [ $MODF -ne 0 ]; then
   echo "removing again modules from  '$ALLMODF'......."
   bin/busybox rm ./*$YAINITKERNVER-$EXTENT*.sfs
 fi
#

