#!bin/busybox ash
#read_initrdvar_file
EXTENT="$1"
MODF=0
ALLMODF=""

.  yainitdefaults

 

if [ "$INITRD" != "" ]; then
 if [ "$EXTENT" != "" ]; then INITRD="$INITRD-$EXTENT"; fi 
 echo "  initrd name = $INITRD"
 bin/busybox rm ../$INITRD.gz
 bin/busybox sync
 bin/busybox find . | bin/busybox cpio -o -H newc | bin/busybox gzip -f > ../$INITRD.gz
else
 bin/busybox rm ../yainit0.gz
 bin/busybox sync
 bin/busybox find . | bin/busybox cpio -o -H newc | bin/busybox gzip  -f > ../yainit0.gz
fi
 bin/busybox sync
 
 if [ $MODF -ne 0 ]; then
   echo "removing again modules from  '$ALLMODF'......."
   bin/busybox rm ./*$YAINITKERNVER-$EXTENT*.sfs
 fi
#

