#!/bin/busybox ash
if [ "$1" != "" ];then 
 INITRD="$1"
else
 INITRD="rt"
 
fi
echo "  rt-file name = $INITRD"
if [ "$INITRD" != "" ]; then
 bin/busybox rm  $INITRD.tar.lzma
 bin/busybox sync
 BUSYBOXES=`bin/busybox ls -1 bin/busybox-* | bin/busybox tr "\n" " " `
 OTHERDIRS=`bin/busybox ls -1d sbin lib usr opt  | bin/busybox tr "\n" " " `
 ./bin/busybox tar -cvf $INITRD.tar   $BUSYBOXES $OTHERDIRS 
 lzma  -9evf $INITRD.tar
else
 echo "No valid spec for tarball file!"
fi
 bin/busybox sync

#fi x86 bin/busybox-x86mmx  bin/busybox-k6p3  bin/busybox-k7p4 bin/busybox-k8p5 bin/busybox-k9c2 bin/busybox-atom bin/busybox-corex /busybox-coreavx bin/busybox-k5 bin/busybox-k6 bin/busybox-k7 bin/busybox-k8 bin/busybox-k9 bin/busybox-k10 bin/busybox-k15 > $INITRD.tar

