#!bin/busybox ash
# (C) Dieter Miosga 08.2013 - 31.10.2013 
EXTENT="$1"
MODF=0
ALLMODF=""
MKEXTENT="xz"
ext=""
ALLEXTENTS=""

. initrdvarfile

set_extents()
{
  
  ALLEXTENTS=""
  ALLMODF=`bin/busybox ls -1 ../zp-$YAINITKERNVER-*-$MKEXTENT.sfs 2>/dev/null`
  for MODF in $ALLMODF; do
    ext="`echo $MODF | /bin/busybox cut -f3 -d-  2>/dev/null`"
    echo "found extent : '$ext'"
    ALLEXTENTS="$ext $ALLEXTENTS"
  done 
  
}

set_kernelmodules()
{

  MODF=0
  ALLMODF=""
  if [ "$EXTENT" = "all" ]; then EXTENT=""; fi
  echo "searching kernelmodfile for '$YAINITKERNVER-$EXTENT-$MKEXTENT'"
  ALLMODF=`bin/busybox ls -1 ../*$YAINITKERNVER-$EXTENT-$MKEXTENT.sfs 2>/dev/null`
  if [ "$ALLMODF" != "" ]; then
    
    MODF=`echo "$ALLMODF" | bin/busybox wc -l 2>/dev/null`
    if [ $MODF -ne 1 ]; then 
       echo "none or more than 1 kernelmodfile!"
    fi
     echo "installing modules from '$ALLMODF'......."
     bin/busybox cp -f  $ALLMODF  ./
     bin/busybox sync  
    
  else
     echo "For '$EXTENT' no kernelmodfile  '$ALLMODF' found!"
  fi
  
}

set_modules_installed()
{
    WHITELIST_MODULES="`/bin/busybox lsmod  2>/dev/null| /bin/busybox tr  ",\n" " " 2>/dev/null| /bin/busybox  tr -d  "\t\n" 2>/dev/null`"
    ALLMODULES="`/bin/busybox find squashfs-root/ -name "*.ko" 2>/dev/null`"
    echo " setting modules variables for : "
    echo $WHITELIST_MODULES
    MODULES_INSTALLED=""
    for file in $ALLMODULES; do
      filename=`/bin/busybox basename $file 2>/dev/null| /bin/busybox cut -f1 -d. 2>/dev/null`
      found=""
      for module in $WHITELIST_MODULES; do
        module=`echo $module | /bin/busybox tr -d " " 2>/dev/null`
        if [ "$filename" = "$module" ]; then
          found=true
        fi
      done
      if [ "$found" != "" ]; then  
         echo "Adding -->  $filename file $file "
         MODULES_INSTALLED="$filename $MODULES_INSTALLED"
      fi  
    done
    echo MODULES_INSTALLED=\"$MODULES_INSTALLED\"  > ./MODULES_INSTALLED
}

WHITELIST_MODULES=""
MODULES_INSTALLED=""

install_current_kernelmodules()
{
  local module file found filename

  if [ $MODF -eq 1 ]; then
    ALLMODF=`bin/busybox ls -1 ./*$YAINITKERNVER-$EXTENT-$MKEXTENT.sfs 2>/dev/null`
    unsquashfs $ALLMODF
    RC=$?
    if [ $RC != 0  ]; then 
      echo "Error unsquashing / unpacking '$ALLMODF' : '$RC' !"
      return 1
    fi
    module=""
    file=""
    filename=""
    WHITELIST_MODULES=""
    MODULES_INSTALLED=""
    if [ -e MODULES_INSTALLED ]; then
    .  MODULES_INSTALLED
    fi
    if [ "$MODULES_INSTALLED" != "" ]; then WHITELIST_MODULES=$MODULES_INSTALLED; fi 
    if [ "$MODULES_INSTALLED" = "" ]; then 
      set_modules_installed  
    fi
    ALLMODULES="`/bin/busybox find squashfs-root/ -name "*.ko" 2>/dev/null`"
      MODULES_INSTALLED=""
      for file in $ALLMODULES; do
        filename=`/bin/busybox basename $file 2>/dev/null| /bin/busybox cut -f1 -d. 2>/dev/null`
        found=""
        for module in $WHITELIST_MODULES; do
          module=`echo $module | /bin/busybox tr -d " " 2>/dev/null`
          if [ "$filename" = "$module" ]; then
            found=true
            #echo "found -->  module=$module <-->  filename=$filename  "
          fi
        done
        if [ "$found" = "" ]; then  
           #echo "delete --> file=$file   filename=$filename  "
           /bin/busybox rm -f $file   2>/dev/null
        else
           echo "Adding -->  $filename : $file "
           MODULES_INSTALLED="$MODULES_INSTALLED $filename"
        fi  
      done
      mksquashfs ./squashfs-root modlocal-$YAINITKERNVER-$EXTENT-gz.sfs 
      /bin/busybox rm -fR ./squashfs-root  $ALLMODF
  else
     echo "For '$EXTENT' no kernelmodfile  '$ALLMODF' found to unpack and adapt!"
  fi
}

if [ "$EXTENT" != "" ]; then
  ALLEXTENTS=$EXTENT
  if [ "$EXTENT" = "all" ]; then set_extents; fi
  if [ "$2" != "" ]; then ALLEXTENTS="$@"; fi
  for ext in $ALLEXTENTS; do 
   EXTENT=$ext
   set_kernelmodules
   install_current_kernelmodules
  done
fi 

#

