#!bin/busybox ash
# (C) Dieter Miosga 08.2013 - 31.10.2013 
EXTENT="$1"
MODE="$2"
MODF=0
MKEXTENT="xz"
ALLMODF=""
ALLMKEXTENTS="gz xz bz2 lzma lz"

if [ -e yainitdefaults ]; then
  source yainitdefaults
else
  echo "essential parameters from file 'yainitdefault' cannot be read!"
  echo "exiting (127)"
  exit 127  
fi

if [ "`echo "$ALLMKEXTENTS" | bin/busybox grep "$EXTENT" 2>/dev/null`" != "" ]; then
  ALLMODF="`bin/busybox ls -1  *$YAINITKERNVER-*.tar 2>/dev/null`"
  for FILE in $ALLMODF; do
  case $EXTENT in
    gz)
      gzip  -vf9 < $FILE >  $FILE.gz
      RC=$?
    ;;
    bz2)
      bzip2 -zfv9  $FILE
      RC=$?
    ;;
    xz)
      xz -zfev9  $FILE
      RC=$?
    ;;
    lzma)
      lzma -zfev9  $FILE
      RC=$?
    ;;
    #lz)
    #  :
    #;;    
  esac
  done
  exit $RC
fi

ext=""
ALLEXTENTS=""
ALLMODF=""


set_extents()
{
  
  ALLEXTENTS=""
  ALLMODF=`bin/busybox ls -1 ../archives/zp-$YAINITKERNVER-*-$MKEXTENT.sfs 2>/dev/null`
  for MODF in $ALLMODF; do
    ext="`echo $MODF | /bin/busybox cut -f3 -d-  2>/dev/null`"
    echo "found extent : '$ext'"
    ALLEXTENTS="$ext $ALLEXTENTS"
  done 
  
}

set_kernelmodules()
{

  MODF=0
  ALLMODF=""
  if [ "$EXTENT" = "all" ]; then EXTENT=""; fi
  echo "searching kernelmodfile for '$YAINITKERNVER-$EXTENT-$MKEXTENT'"
  ALLMODF=`bin/busybox ls -1 ../archives/*$YAINITKERNVER-$EXTENT-$MKEXTENT.sfs 2>/dev/null`
  if [ "$ALLMODF" != "" ]; then
    
    MODF=`echo "$ALLMODF" | bin/busybox wc -l 2>/dev/null`
    if [ $MODF -ne 1 ]; then 
       echo "none or more than 1 kernelmodfile : '$ALLMODF'  !"
    fi
     echo "installing modules from '$ALLMODF'......."
     bin/busybox cp -f  $ALLMODF  ./
     bin/busybox sync  
    
  else
     echo "For '$EXTENT' no kernelmodfile  '$ALLMODF' found!"
  fi
  
}

LOCAL_MODULES=""
MODULES_INSTALLED="$DEFAULT_ALLDRIVERS"


set_modules_installed()
{
    if [ -e MODULES_LOCAL ]; then
       . MODULES_LOCAL
    else
      exec generate-moduleslocal
       . MODULES_LOCAL
    fi
    LOCAL_MODULES=$MODULES_LOCAL
    
    ALLMODULES="`bin/busybox find squashfs-root/ -name "*.ko" 2>/dev/null`"
    echo " setting modules variables for : "
    echo $LOCAL_MODULES
    MODULES_INSTALLED=""
    for file in $ALLMODULES; do
      filename=`bin/busybox basename $file 2>/dev/null| /bin/busybox cut -f1 -d. 2>/dev/null`
      found=""
      for module in $LOCAL_MODULES; do
        module=`echo $module | bin/busybox tr -d " " 2>/dev/null`
        if [ "$filename" = "$module" ]; then
          found=true
          break
        fi
      done
      if [ "$found" != "" ]; then  
         echo "Adding -->  $filename file $file "
         MODULES_INSTALLED="$filename $MODULES_INSTALLED"
      fi  
    done
    echo MODULES_INSTALLED=\"$MODULES_INSTALLED\"  > ./MODULES_INSTALLED
}


install_current_kernelmodules()
{
  local module file found filename

  if [ $MODF -eq 1 ]; then
    ALLMODF=`bin/busybox ls -1 ./*$YAINITKERNVER-$EXTENT-$MKEXTENT.sfs 2>/dev/null`
    unsquashfs $ALLMODF
    RC=$?
    if [ $RC != 0  ]; then 
      echo "Error unsquashing / unpacking '$ALLMODF' : '$RC' !"
      return 1
    fi
    module=""
    file=""
    filename=""
    LOCAL_MODULES=""
    MODULES_INSTALLED=""
    if [ "$DEFAULT_ALLDRIVERS" = "" ]; then
      source yainitdefaults
      #MODULES_INSTALLED="$DEFAULT_ALLDRIVERS"
    fi
    MODULES_INSTALLED="$DEFAULT_ALLDRIVERS"
    if [ "$MODULES_INSTALLED" != "" ]; then 
       LOCAL_MODULES="$MODULES_INSTALLED"
    #else 
     # set_modules_installed  
    fi
    ALLMODULES="`bin/busybox find squashfs-root/ -name "*.ko" 2>/dev/null`"
      MODULES_INSTALLED=""
      for file in $ALLMODULES; do
        filename=`bin/busybox basename $file 2>/dev/null| /bin/busybox cut -f1 -d. 2>/dev/null | /bin/busybox tr "-" "_"  2>/dev/null`
        echo "-->  $filename : $file "
        found=""
         if [ "$MODE" != "" ]; then  
           echo "Adding -->  $filename : $file "
           MODULES_INSTALLED="$MODULES_INSTALLED $filename"
         else
            found="`echo "$DEFAULT_ALLDRIVERS" | bin/busybox grep "$filename" 2>/dev/null`"
            if [ "$found" != "" ]; then
               echo "Adding -->  $filename : $file "
               MODULES_INSTALLED="$MODULES_INSTALLED $filename"
            else
               echo "deleting --> file=$file   filename=$filename  "
               bin/busybox rm -f $file   2>/dev/null
            fi  
         fi
      done
      mkdir -p lib
      mkdir -p lib/modules
      mkdir -p lib/modules/$YAINITKERNVER-$EXTENT
      mkdir -p lib/modules/$YAINITKERNVER-$EXTENT/kernel
      bin/busybox mv  -f  squashfs-root/*  lib/modules/$YAINITKERNVER-$EXTENT/kernel
      bin/busybox tar -cvf libmodules-$YAINITKERNVER-$EXTENT.tar  lib
      #xz -zfev9 libmodules-$YAINITKERNVER-$EXTENT.tar
      bin/busybox rmdir  squashfs-root 
      bin/busybox rm -fR  lib 
      bin/busybox rm -f $ALLMODF
  else
     echo "For '$EXTENT' no kernelmodfile  '$ALLMODF' found to unpack and adapt!"
  fi
}

if [ "$EXTENT" != "" ]; then
  ALLEXTENTS=$EXTENT
  if [ "$EXTENT" = "all" ]; then set_extents; fi
  if [ "$2" != "" ]; then ALLEXTENTS="$@"; fi
  for ext in $ALLEXTENTS; do 
   EXTENT=$ext
   set_kernelmodules
   ./mkinitrdgz $EXTENT
   bin/busybox sync
   ALLMODF=`bin/busybox ls -1 ./*.sfs 2>/dev/null`
   if [ "$ALLMODF" != "" ]; then   
     echo "removing : '$ALLMODF' ......."
      bin/busybox rm  $ALLMODF
   else
     echo "For '$EXTENT' no kernelmodfile(s)  '$ALLMODF' found to clean away"
   fi
  done
fi 

#

